/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'johnfulton' at '14/03/16 7:46 PM' with Gradle 2.11
 *
 * @author johnfulton, @date 14/03/16 7:46 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
